### ISSUE TITLE
Backups Piling Up In Hourly Folder

### ISSUE THREAD

**Issue by jalandoak** [adamfeuer/rotate-backups#6]
I'm running the script as a cron job.

Running it from the CLI as:  ./rotate-backups.py > /dev/null

Produces:
Traceback (most recent call last):
  File "./rotate-backups.py", line 335, in <module>
    account.rotate_hourlies()
  File "./rotate-backups.py", line 223, in rotate_hourlies
    hourly.remove()
  File "./rotate-backups.py", line 284, in remove
    os.remove(self.path_to_file)
OSError: [Errno 21] Is a directory: '/home/minecraft/mcbackup/worldarchives/world/hourly/world-2013-04-03-1900.tar.bz2'

Ubuntu Server 12.04

Jeff

**Comment by dmr** [comment]
Is this issue resolved?

**Comment by jalandoak** [comment]
I never got it to work. And I'm not running a server anymore, so I can't give any other suggestions. Sorry.

**Comment by dmr** [comment]
@adamfeuer Close this?
